package com.wzh.blog.media;

import java.util.regex.Pattern;

/**
 * Validates provider-relative keys before an adapter is called. Keys are
 * generated by the server and are never allowed to escape a provider prefix.
 */
public final class ObjectKeyPolicy {

    private static final Pattern CONTROL_CHARACTER = Pattern.compile("[\\u0000-\\u001F\\u007F]");

    private ObjectKeyPolicy() {
    }

    public static String requireSafe(String objectKey) {
        if (objectKey == null || objectKey.isBlank()) {
            throw new IllegalArgumentException("Object key must not be blank");
        }
        if (objectKey.length() > 512
                || objectKey.startsWith("/")
                || objectKey.startsWith("\\")
                || objectKey.contains("\\")
                || CONTROL_CHARACTER.matcher(objectKey).find()) {
            throw new IllegalArgumentException("Unsafe object key");
        }
        String[] segments = objectKey.split("/");
        for (String segment : segments) {
            if (segment.isBlank() || ".".equals(segment) || "..".equals(segment)) {
                throw new IllegalArgumentException("Unsafe object key");
            }
        }
        return objectKey;
    }
}
