server {
    listen 80;
    listen [::]:80;
    server_name api-test.14-103-129-219.sslip.io;
    client_max_body_size 25m;

    location / {
        proxy_pass http://172.17.0.1:8090;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name api.ticastr.cn;

    location ^~ /.well-known/acme-challenge/ {
        root /www/acme;
    }

    location / {
        return 301 https://api.ticastr.cn$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api.ticastr.cn;
    client_max_body_size 25m;

    ssl_certificate /usr/local/openresty/nginx/conf/ssl/ticastr/api.ticastr.cn.fullchain.pem;
    ssl_certificate_key /usr/local/openresty/nginx/conf/ssl/ticastr/api.ticastr.cn.privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:TicastrSSL:10m;
    ssl_session_timeout 10m;

    location / {
        proxy_pass http://172.17.0.1:8090;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
    }
}
